android.useAndroidX=true

magrathea.group=saien.magrathea
# x-release-please-start-version
magrathea.version=0.1.0-alpha.11
# x-release-please-end
magrathea.pom.url=https://github.com/senseFy/magrathea

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
