blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/senseFy/magrathea/security/advisories/new
    about: Report vulnerabilities and sensitive security details privately.
